apiVersion: management.loft.sh/v1
kind: Team
metadata:
  name: echo-dev
spec:
  displayName: echo-dev
  users:
    - admin
  groups:
    - km-demos:echo-app
  clusterRoles:
    - name: loft-management-project-viewer
    - name: vcluster-instance-use
  access:
    - name: loft-access
      verbs:
        - get
        - bind
      subresources:
        - clusters
      teams:
        - echo-dev
