kind: VirtualClusterTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: preview-template
spec:
  displayName: preview-template
  owner:
    user: admin
  template:
    metadata:
      labels:
        loft.sh/import-argocd: 'true'
      annotations:
        sleepmode.loft.sh/delete-after: '72000'
        sleepmode.loft.sh/sleep-after: '6000'
    access:
      rules:
        - users:
            - admin
          clusterRole: cluster-admin
    helmRelease:
      chart: {}
      values: |-
        nodeSelector:
          kubernetes.io/arch: arm64
        sync:
          ingresses:
            enabled: true
        isolation:
          enabled: true
          networkPolicy:
            enabled: false
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin