kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: preview
spec:
  displayName: preview
  owner:
    user: admin
  quotas:
    project:
      spaceinstances.active.template=isolated-space: '4'
      spaceinstances.template=isolated-space: '8'
      requests.cpu: '8'
      virtualclusterinstances.active.template=preview-template: '4'
      virtualclusterinstances.template=preview-template: '8'
    user:
      virtualclusterinstances.template=preview-template: '2'
      spaceinstances.template=isolated-space: '2'
      requests.cpu: '4'
  allowedClusters:
    - name: '*'
  allowedTemplates:
    - kind: SpaceTemplate
      group: storage.loft.sh
      name: loft-cluster
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: preview-template
  members:
    - kind: User
      group: storage.loft.sh
      name: admin
      clusterRole: loft-management-project-user
    - kind: Team
      group: storage.loft.sh
      name: echo-dev
      clusterRole: loft-management-project-user
    - kind: Team
      group: storage.loft.sh
      name: km-demosecho-app
      clusterRole: loft-management-project-user
  access:
    - name: loft-access
      verbs:
        - get
      subresources:
        - members
        - clusters
        - templates
        - chartinfo
        - charts
      users:
        - admin
      teams:
        - echo-dev
        - km-demosecho-app
    - name: loft-admin-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      users:
        - admin
  argoCD:
    enabled: true
    cluster: loft-cluster
    namespace: argocd
    project:
      enabled: true
    sso:
      enabled: true
      host: https://argocd.k8s.kurtmadel.com
      assignedRoles:
        - role:readonly