kind: ClusterRoleTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: vcluster-instance-use
spec:
  displayName: vcluster use
  description: Allows get, watch, list and use for all vcluster instances in the project.
  owner:
    user: admin
  management: true
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin
  clusterRoleTemplate:
    metadata:
      creationTimestamp: null
    rules:
      - verbs:
          - get
          - watch
          - list
          - use
        apiGroups:
          - management.loft.sh
        resources:
          - virtualclusterinstances
