apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: REPO_NAME-pr
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: km-demos
        # The Github repository
        repo: REPO_NAME
        # (optional) use a GitHub App to access the API instead of a PAT.
        #appSecretName: github-app-repo-creds
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - preview
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'REPO_NAME-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/km-demos/REPO_NAME.git'
        targetRevision: '{{head_sha}}'
        path: helm-chart/
        helm:
          parameters:
          - name: "image.repository"
            value: ghcr.io/km-demos/REPO_NAME
          - name: "image.tag"
            value: "{{head_short_sha}}"
          - name: "image.args.text"
            value: "Hello from REPO_NAME pr-{{number}} commit {{head_short_sha}}"
          - name: "ingress.hosts[0].host"
            value: REPO_NAME-pr-{{number}}.previews.k8s.kurtmadel.com
          - name: "ingress.tls[0].hosts[0]"
            value: REPO_NAME-pr-{{number}}.previews.k8s.kurtmadel.com
          - name: "ingress.tls[0].secretName"
            value: preview-tls
      project: "loft-preview"
      destination:
        server: LOFT_URL/kubernetes/project/preview/virtualcluster/REPO_NAME-pr-{{number}}
        namespace: preview-REPO_NAME
      info:
        - name: Preview App Link
          value: >-
            https://REPO_NAME-pr-{{number}}.previews.k8s.kurtmadel.com
        - name: GitHub PR
          value: >-
            https://github.com/km-demos/REPO_NAME/pull/{{number}}