name: Actions Runner Controller Demo
on:
  workflow_dispatch:
    inputs:
      loft-cli-version:
        description: 'Loft CLI version to use'
        default: "v3.2.4"

env:
  LOFT_CLI_VERSION: ${{ inputs.loft-cli-version || 'v3.2.4' }}

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "Meg is awesome 🎉 This job uses runner scale set runners!"
    
    - name: checkout
      uses: actions/checkout@v4

    - name: Install Loft CLI
      uses: loft-sh/setup-loft@v2
      with:
        version: ${{ env.LOFT_CLI_VERSION }}
        url: loft.loft.svc.cluster.local
        insecure: true
        # Specify your Loft access key here
        access-key: ${{ secrets.KUBEPI_LOFT_ACCESS_KEY }}

    - name: Create Preview Project
      run: |
        loft use management
        kubectl apply -f ./loft/vcluster-use-role.yaml
        kubectl apply -f ./loft/echo-dev-team.yaml
        kubectl apply -f ./loft/preview-vcluster-template.yaml
        kubectl apply -f ./loft/preview-project.yaml
        kubectl apply -f ./loft/ghcr-login-projectsecret.yaml

