name: Actions Runner Controller Demo
on:
  workflow_dispatch:
    inputs:
      loft-cli-version:
        description: 'Loft CLI version to use'
        default: "v3.2.4"

env:
  LOFT_CLI_VERSION: ${{ inputs.loft-cli-version || 'v3.2.4' }}

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "Meg is awesome 🎉 This job uses runner scale set runners!"

    - name: Install Loft CLI
      uses: loft-sh/setup-loft@v2
      with:
        version: ${{ env.LOFT_CLI_VERSION }}
        url: https://loft.kubepi.cluster
        insecure: true
        # Specify your Loft access key here
        access-key: ${{ secrets.KUBEPI_LOFT_ACCESS_KEY }}

