name: Create Loft preview project

on:
  workflow_dispatch:
    inputs:
      loft-cli-version:
        description: 'Loft CLI version to use'
        default: "v3.2.4"

env:
  LOFT_CLI_VERSION: ${{ inputs.loft-cli-version || 'v3.2.4' }}
# define a job that creates a vcluster using the Loft CLI.
jobs:
  create-preview-project:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Loft CLI
        uses: loft-sh/setup-loft@v2
        with:
          version: ${{ env.LOFT_CLI_VERSION }}
          url: ${{ secrets.LOFT_URL }}
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_DEV_CLUSTER_ACCESS_KEY }}

      - name: Create Preview Project
        run: |
          loft use management
          kubectl apply -f ./loft/vcluster-read-role.yaml
          kubectl apply -f ./loft/echo-dev-team.yaml
          kubectl apply -f ./loft/preview-vcluster-template.yaml
          kubectl apply -f ./loft/preview-project.yaml
