name: Create Loft preview project

on:
  workflow_dispatch:
    inputs:
      vcluster-name:
        description: 'Name of vcluster to create'
        default: "my-vcluster"

env:
  VCLUSTER_NAME: ${{ inputs.vcluster-name || 'my-vcluster' }}
# define a job that creates a vcluster using the Loft CLI.
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Loft CLI
        uses: loft-sh/setup-loft@v2
        with:
          version: v3.2.4
          url: ${{ secrets.LOFT_URL }}
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_DEV_CLUSTER_ACCESS_KEY }}

      - name: Create Cluster
        run: |
          loft use management
          kubectl apply -f ./loft/echo-dev-team.yaml
          kubectl apply -f ./preview-vcluster-template.yaml
          kubectl apply -f ./preview-project.yaml
