name: delete argocd echo app
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Echo App Repo to delete'
        type: string
        default: 'echo-app'
      cluster-name:
        description: 'Name of GKE cluster to delete echo app from'
        default: "demo-cluster"
      gcp-region:
        type: choice
        description: 'GCP region of cluster'
        default: "us-east5"
        options:
        - us-east5
        - us-central1
        - us-east4
      gcp-zone:
        type: choice
        description: 'GCP zone of cluster'
        default: "a"
        options: 
        - a
        - b
        - c

env:
  REPO_NAME: ${{ github.event.inputs.repo_name || 'echo-app' }}
  CLUSTER_NAME: ${{ github.event.inputs.cluster-name || 'demo-cluster' }}
  GCP_REGION: ${{ github.event.inputs.gcp-region || 'us-east5' }}
  GCP_ZONE: ${{ github.event.inputs.gcp-region || 'us-east5' }}-${{ github.event.inputs.gcp-zone || 'a' }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_DNS_ZONE: examples-kurtmadel

jobs:
  create-argocd-echo-app:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Generate km-demos GitHub App token
      id: generate_token
      uses: tibdex/github-app-token@v1.8.0
      with:
          app_id: ${{ secrets.KM_DEMOS_GITHUB_APP_ID }}
          private_key: ${{ secrets.KM_DEMOS_GITHUB_APP_KEY }}
    - name: github-cleanup
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/km-demos/$REPO_NAME
        gh api \ \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer ${{ secrets.KM_MANAGE_PACKAGES_TOKEN }}" \
          /orgs/km-demos/packages/container/$REPO_NAME
    - id: 'gcp-auth'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1.1.1
      with:
        workload_identity_provider: ${{ secrets.WIF_POOL }}
        service_account: ${{ secrets.SA_EMAIL }}
    - id: get-credentials
      uses: google-github-actions/get-gke-credentials@v1.0.2
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.GCP_ZONE }}
    - id: gcp-cleanup
      run: |
        kubectl delete application -n argo-cd $REPO_NAME
        kubectl delete ns $REPO_NAME
        gcloud dns record-sets delete $REPO_NAME.examples.kurtmadel.com. --type=A --zone=$GCP_DNS_ZONE --project=$GCP_PROJECT_ID