name: "Argo CD Upgrade/Install"

on:
  workflow_dispatch:
    inputs:
      target-environment:
        type: choice
        description: Target environment for Argo CD
        options: 
        - KUBEPI
        - GKE
      loft-cli-version:
        description: 'Loft CLI version to use'
        default: "v3.2.4"

env:
  LOFT_CLI_VERSION: ${{ inputs.loft-cli-version || 'v3.2.4' }}

jobs:
  upgrade-install:
    name: upgrade-install-argocd
    environment:
      name: ${{ inputs.target-environment }}
    runs-on: arc-runner-set
    permissions:
      id-token: write
      contents: read 
    steps:
      - id: checkout
        uses: actions/checkout@v4  

      - id: install-loft-cli
        uses: loft-sh/setup-loft@v2
        with:
          version: ${{ env.LOFT_CLI_VERSION }}
          url: ${{ vars.LOFT_URL }}
          insecure: true
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - id: use-cluster
        run: |
          loft use cluster loft-cluster
          kubectl get pods -A